web:
  build: .
  command: chalice local --host 0.0.0.0 --port 8000 --stage docker
  ports:
    - "8000:8000"
  volumes:
    - .:/code
  links:
    - mongodb
    
mongodb:
  image: mongo:4.0.5
  volumes:
    - './data:/data/db'
  ports:
    - "27017:27017"
